eventlog.lo: /Users/leandre/Dropbox/github/eventlog/eventlog.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/leandre/Dropbox/github/eventlog $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/leandre/Dropbox/github/eventlog/eventlog.c -o eventlog.lo 
$(phplibdir)/eventlog.la: ./eventlog.la
	$(LIBTOOL) --mode=install cp ./eventlog.la $(phplibdir)

./eventlog.la: $(shared_objects_eventlog) $(EVENTLOG_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_eventlog) $(EVENTLOG_SHARED_LIBADD)

